### PR TITLE
Changed cursor to be "text" when in text area to be consistent with other text editors

### PR DESCRIPTION
**Pull request by bbb651**
I can't really test it because I'm having some issues with building, but I think I think it would make it more consistent with other text editors.

### CODE REVIEW

**Review by bbodi — APPROVED** [review]

**Comment by bbodi** [comment]
Hehe, thanks for noticing it :)

**Comment by bbodi** [comment]
btw what is your issue with building?

**Comment by bbb651** [comment]
When I build it using `compile_and_run.bat` semi-works, but I'm getting in the javascript console every time I move my mouse
```
Uncaught TypeError: wasm_bindgen.handle_mouse_move is not a function
    on_drag http://localhost:5000/notecalc:395
notecalc:395:70
```
Which makes everything that relies on it break

**Comment by bbodi** [comment]
yes, use the ``localhost:5000/notecalc?debug`` url.
There are 2 wasm files:
- the one which is compiled every time you compile the project, this one is used by the ``?debug`` url
- the one which is used by the GitHub Pages, it can be found in the asset folder, and I have to explicitly copy the file there when I create a release. I did it so minimize the amount of data git has to store, so I have to upload a wasm file to the repository only when a release is done.

**Pull request merged**
